# Generated by Django 3.2.25 on 2026-09-14 05:23

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0007_monthlytask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('plate_number', models.CharField(blank=True, default='', max_length=20)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('battery_capacity_kwh', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ev_vehicle',
                'ordering': ['brand', 'plate_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChargingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_type', models.CharField(choices=[('AC', 'AC'), ('DC', 'DC')], default='AC', max_length=2)),
                ('charge_date', models.DateField(db_index=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('start_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('end_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('price_per_kwh', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('battery_capacity_kwh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charging_record', to='expense.expenserecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_records', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charging_records', to='evcharge.vehicle')),
            ],
            options={
                'db_table': 'ev_charging_record',
                'ordering': ['-charge_date', '-created_at'],
            },
        ),
    ]
